import { AlgorithmConfig } from '../algorithm.types';

// TODO: figure out how to edit this page from /dashboard/page
export const radixSortConfig: AlgorithmConfig = {
  sceneName: 'RadixSort',
  title: 'Sorting Algorithm',
  description: `<a href='https://en.wikipedia.org/wiki/Pathfinding' class="link-hover">Radix Sort</a> is considered one of the fastests sorting algorithms. It avoids comparison by creating and <a href='https://en.wikipedia.org/wiki/Distribution_sort' class="link-hover">distributing</a> elements into buckets (or bins) according to their <a href='https://en.wikipedia.org/wiki/Radix' class="link-hover">radix</a>. This bucketing proces is repeated for each digit, while preserving the ordering of the prior step, until all digits have been considered. Radix sort can be applied to data that can be sorted <a href='https://en.wikipedia.org/wiki/Lexicographical_order' class="link-hover">lexicographically</a>.`,
  modalDescription: [
    { text: 'Radix Sort', link: 'https://en.wikipedia.org/wiki/Radix_sort' },
    { text: ' is a non-comparative sorting algorithm that sorts data by processing individual digits or characters. Unlike ' },
    { text: 'comparison-based sorts', link: 'https://en.wikipedia.org/wiki/Comparison_sort' },
    { text: ' (like QuickSort or MergeSort), radix sort avoids comparisons entirely, making it exceptionally fast for certain data types.' },
    { text: '<br/><br/><b>Two Approaches:</b><br/>' },
    { text: '• ' },
    { text: 'LSD (Least Significant Digit)', link: 'https://en.wikipedia.org/wiki/Radix_sort#Least_significant_digit' },
    { text: ' — Processes from the rightmost digit to the left. This is the approach used in this visualization. LSD radix sort is ' },
    { text: 'stable', link: 'https://en.wikipedia.org/wiki/Sorting_algorithm#Stability' },
    { text: ', meaning equal elements maintain their relative order.<br/>' },
    { text: '• ' },
    { text: 'MSD (Most Significant Digit)', link: 'https://en.wikipedia.org/wiki/Radix_sort#Most_significant_digit' },
    { text: ' — Processes from the leftmost digit to the right. Often implemented recursively and useful for variable-length strings.' },
    { text: '<br/><br/><b>How LSD Radix Sort Works:</b><br/>' },
    { text: '1. Start with the least significant digit (rightmost).<br/>' },
    { text: '2. ' },
    { text: 'Distribute', link: 'https://en.wikipedia.org/wiki/Distribution_sort' },
    { text: ' all elements into 10 bins (0-9) based on the current digit.<br/>' },
    { text: '3. Collect elements from bins in order (0 through 9), preserving the order within each bin.<br/>' },
    { text: '4. Move to the next digit position (one place left).<br/>' },
    { text: '5. Repeat until all digit positions have been processed.' },
    { text: '<br/><br/><b>Time Complexity:</b><br/>' },
    { text: 'Radix sort runs in ' },
    { text: 'O(n × k)', link: 'https://en.wikipedia.org/wiki/Time_complexity' },
    { text: ' time, where <i>n</i> is the number of elements and <i>k</i> is the number of digits. For fixed-length keys (like 5-digit ZIP codes), this becomes effectively ' },
    { text: 'O(n)', link: 'https://en.wikipedia.org/wiki/Time_complexity#Linear_time' },
    { text: ' — linear time!' },
    { text: '<br/><br/><b>Space Complexity:</b> O(n + k) — requires extra space for the bins.' },
    { text: '<br/><br/><b>Why Use Bins as Queues?</b><br/>' },
    { text: 'Each bin is implemented as a ' },
    { text: 'queue (FIFO)', link: 'https://en.wikipedia.org/wiki/Queue_(abstract_data_type)' },
    { text: '. This is crucial for stability — elements entering a bin first will leave first, preserving their relative order from previous passes.' },
    { text: '<br/><br/><b>When to Use Radix Sort:</b><br/>' },
    { text: '• Sorting integers or fixed-length strings<br/>' },
    { text: '• Large datasets where comparison overhead is significant<br/>' },
    { text: '• When stability is required<br/>' },
    { text: '• Data with a limited range of digits/characters' },
    { text: '<br/><br/><b>When NOT to Use Radix Sort:</b><br/>' },
    { text: '• Floating-point numbers (without special encoding)<br/>' },
    { text: '• Variable-length data with long maximum length<br/>' },
    { text: '• Memory-constrained environments (not in-place)' },
    { text: '<br/><br/><b>Real-World Applications:</b><br/>' },
    { text: '• <b>Postal Services:</b> Sorting mail by ZIP codes (exactly what this demo shows!)<br/>' },
    { text: '• <b>Phone Numbers:</b> Organizing contact lists<br/>' },
    { text: '• <b>IP Addresses:</b> Network routing tables<br/>' },
    { text: '• <b>Suffix Arrays:</b> Used in ' },
    { text: 'bioinformatics', link: 'https://en.wikipedia.org/wiki/Bioinformatics' },
    { text: ' for DNA sequence analysis' },
    { text: '<br/><br/><b>Comparison with Other Sorts:</b><br/>' },
    { text: '• ' },
    { text: 'QuickSort', link: 'https://en.wikipedia.org/wiki/Quicksort' },
    { text: ' — O(n log n) average case, in-place, but not stable<br/>' },
    { text: '• ' },
    { text: 'MergeSort', link: 'https://en.wikipedia.org/wiki/Merge_sort' },
    { text: ' — O(n log n), stable, but requires O(n) extra space<br/>' },
    { text: '• ' },
    { text: 'Counting Sort', link: 'https://en.wikipedia.org/wiki/Counting_sort' },
    { text: ' — Related algorithm that radix sort often uses internally for each digit pass' }
  ],
  pseudocodes: {
    OnRadixStateChanged: {
      title: "Transition to next sorting phase",
      code: `<span class="keyword">switch</span> (state) {<br/>&nbsp;&nbsp;<span class="keyword">case</span> <span class="string">'idle'</span>: state ← <span class="string">'selectDigit'</span><br/>&nbsp;&nbsp;<span class="keyword">case</span> <span class="string">'selectDigit'</span>: state ← <span class="string">'distribute'</span><br/>&nbsp;&nbsp;<span class="keyword">case</span> <span class="string">'distribute'</span>: state ← <span class="string">'collect'</span><br/>&nbsp;&nbsp;<span class="keyword">case</span> <span class="string">'collect'</span>: state ← <span class="string">'advance'</span><br/>&nbsp;&nbsp;<span class="keyword">case</span> <span class="string">'advance'</span>: state ← isComplete ? <span class="string">'done'</span> : <span class="string">'selectDigit'</span><br/>}`,
      tooltip: `Radix sort transitions through phases: Select digit → Distribute to bins → Collect from bins → Advance to next digit. This cycle repeats until all digits are processed.`,
    },
    OnDigitSelected: {
      title: "Select current digit position (LSD)",
      code: `<span class="comment">// Least Significant Digit first</span><br/>activeDigit ← activeDigit + 1<br/>position ← digits.length - activeDigit`,
      tooltip: `In LSD Radix Sort, we start from the rightmost digit (least significant) and move left. This ensures stable sorting — elements with the same digit maintain their relative order from previous passes.`,
    },
    OnLetterMovedToBin: {
      title: "Distribute items into digit bins",
      code: `<span class="keyword">for each</span> item <span class="keyword">in</span> items {<br/>&nbsp;&nbsp;digit ← item.getDigitAt(activeDigit)<br/>&nbsp;&nbsp;bins[digit].<span class="fn">enqueue</span>(item)<br/>}<br/><span class="fn">emit</span>(<span class="string">'DistributionComplete'</span>)`,
      tooltip: `Each item is placed into a bin (0-9) based on its current digit value. For example, ZIP code 12345 with activeDigit=0 goes into bin 5 (rightmost digit).`,
    },
    OnLetterCollected: {
      title: "Collect items from bins in order",
      code: `result ← []<br/><span class="keyword">for</span> binIndex <span class="keyword">from</span> 0 <span class="keyword">to</span> 9 {<br/>&nbsp;&nbsp;<span class="keyword">while</span> (bins[binIndex].notEmpty) {<br/>&nbsp;&nbsp;&nbsp;&nbsp;result.<span class="fn">push</span>(bins[binIndex].<span class="fn">dequeue</span>())<br/>&nbsp;&nbsp;}<br/>}<br/><span class="fn">emit</span>(<span class="string">'CollectionComplete'</span>)`,
      tooltip: `Items are collected by draining bins in order (0→9). Since bins are queues (FIFO), the relative order from previous digit passes is preserved — this is what makes radix sort stable.`,
    },
    OnPassComplete: {
      title: "Advance to next digit position",
      code: `activeDigit ← activeDigit + 1<br/><span class="comment">// Clear bins for next pass</span><br/><span class="keyword">for</span> i <span class="keyword">from</span> 0 <span class="keyword">to</span> 9 {<br/>&nbsp;&nbsp;bins[i] ← <span class="keyword">new</span> Queue()<br/>}`,
      tooltip: `After processing one digit, we move to the next position (one place left). If no more digits remain, the items are fully sorted.`,
    },
    OnRadixSortComplete: {
      title: "Sorting complete",
      code: `<span class="keyword">if</span> (activeDigit &gt;= maxDigits) {<br/>&nbsp;&nbsp;state ← <span class="string">'done'</span><br/>&nbsp;&nbsp;<span class="fn">emit</span>(<span class="string">'SortingComplete'</span>)<br/>}`,
      tooltip: `All digit positions have been processed from right to left. The items are now sorted in ascending lexicographic order.`
    },
    OnLettersInitialized: {
      title: "Initialize items for sorting",
      code: `<span class="keyword">function</span> <span class="fn">initializeLetters</span>(zipCodes) {<br/>&nbsp;&nbsp;<span class="keyword">for each</span> zip <span class="keyword">in</span> zipCodes {<br/>&nbsp;&nbsp;&nbsp;&nbsp;digits ← zip.<span class="fn">split</span>(<span class="string">''</span>)<br/>&nbsp;&nbsp;&nbsp;&nbsp;items.<span class="fn">push</span>({ zip, digits })<br/>&nbsp;&nbsp;}<br/>&nbsp;&nbsp;activeDigit ← 0<br/>}`,
      tooltip: `Prepares the ZIP codes for sorting. Each 5-digit code is split into individual digits for radix processing. The algorithm will process from the rightmost digit first.`,
    }
  },
  operations: ['OnDigitSelected', 'OnLetterMovedToBin', 'OnLetterCollected', 'OnPassComplete', 'OnRadixSortComplete', 'OnLettersInitialized'],
  explanationRules: {
    empty: "The objective is to find the goal node",
    hasItems: "TODO",
    default: "TODO"
  }
}
